"""add_creator_category_starred

Revision ID: 22790b4d51d8
Revises: fbbc2f257ae3
Create Date: 2026-04-18 15:13:53.548446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22790b4d51d8'
down_revision: Union[str, None] = 'fbbc2f257ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('creators', sa.Column('starred', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creators', 'starred')
    op.drop_column('creators', 'category')
    # ### end Alembic commands ###
